#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: INCD Design Journal
url: /INCD-Journal
baseurl: /INCD-Journal

# Short bio or description (displayed in the header)
description: An old book, boiled in oil.

